name: RDP

on:

workflow_dispatch:

joba:

secure-rdp:

runs-on: windows-latest timeout-minutes: 3600

steps:

name: Configure Core EDP Settings run: 1

Enable Remote Desktop and disable

Authentication (if needed) Set-ItemProperty Network Level

-Path

olSet\Control\Terminal HKLM\System\CurrentContr

Berver

-Name fDenyTiConnections" -Value 0-Force

-Path Set-ItemProperty

HKLM\System\CurrentContr olSet\Control\Terminal Berver\WinStations RDP-

Tep

-Name "UserAuthentication" -Value 0-Force Set-ItemProperty

-Path

HKLM\System\CurrentContr olSet\Control\Terminal Server\WinStations RDP-

Tep

-Name "SecurityLayer" Value 0 Force

Remove any existing rule with the same name to avoid

duplication

netsh advfirewall firewall delete rule name "RDP-Tailscale

#For testing. allow any any incoming connection on port 3389

netsh advfirewall firewall add rule name "RDP-Tailscale"

dirsin actionsallow protocol TCP localport-3389

(Optional) Restart the Remote Desktop service to ensure changes

take effect Restart-Service -Name TernService -Force

name: Create EDP User with Secure Password

Add-Type AssemblyName System.Security

Bcharset

Upper [char]]]165..90) A-

[char]]197. 1221 Lower

Number

(charl]]148.57)

9 Special [[charl11(33..47) [char|||158..64).

[char]]191..96). [char]](123.12611 # Special characters

SramPassword

Random Count 4

SrawPassword

ScharSet. Upper | Get-

SrawPassword

Bcharset. Lower | Get-

Random Count 4

SrawPassword

ScharSet. Number Get-

Random Count 4

SrawPassword

Scharset Special | Det

Random Count 4 Spassword join lärawPassword fort-

Object Get-Random SnecurePas 1

ConvertTo-SecureString

password -AsPlainText

Force

New-LocalUser

Name "BDP -Password

SsecurePass

Account NeverExpires

Add-

LocalGroupMember Group "Administrators Member HDP

Add-

LocalGroupMember -Group Remote Desktop Users Member RDP

echo

RDP CREDS-User: RDP ।

>>

Password: $password

Senv: GITHUB ENV

if not (Get-

LocalUser Name RDP)

Write-Error

"User creation failed

1

exit 1

name: Install

Tailscale

run: I

StsUrl

"https://pkgs.tailscale.co

m/stable/tailscale-setup-

3.82.0-amd64.msi"

SinstallerPath *Senv: TEMP\tailscale.msi

Invoke-

WebRequest Uri StaUrl

OutFile SinstallerPath

Start-Proc

msiexec.exe ArgumentList

1. "SinstallerPath".

/quiet", "/norestart

Wait

Remove-Item

SinstallerPath Force

name: Establish

Tailocale Connection

run: I

Bring up

Tailscale with the

provided auth key and set

a unique hostname

Senv ProgramFiles\Tasinca

lextailscale.exe up

authkey

secrets.TAILSCALE AUTH KEY

3)-hostname-gh-

zunner-Senv: OITHUB RUN ID

Wait for

Teilscale to assign an IP

Stale Snull

Sretries

while I-not

BtsIP and Bretries it

2011

StsIP&

*Senv:ProgramFiles\Tailsca

Start-Sleep

le\tailscale.exe" ip-4

-Seconda 5

Sretries++

if not IP

Write-Error

Tailscale IP not

assigned. Exiting

echo

exit 1

TAILSCALE IP-StsIP">

Benv: GITHUB ENV

name: Verify MDP

Accessibility

run:

Write-Host

Tailecale IP:

Beny: TAILOCALE IP

Test

connectivity using Test

NetConnection against the

Tailscale IP on port 3389

StestResult

Test-NetConnection

ComputerName

Benv: TAILSCALE IP-Port

3389

if i-not

testResult.TopTestSucceed

ed! E

Write-Error

TCP connection to RDP

port 3389 failed"

exit 1

Write-Host "TOP

connectivity successful

name: Maintain

Connection

run:

Write-Host

RDF ACCESS

"Address:

Write-Host

Benv TAILSCALE IP

Write-Host

"Username: BDF

Write-Host

"Password: Biecho

Senv:BDP CREDS)

Write-Host

Keep runner

active indefinitely (or

until manually cancelled]

while (Strue)|

Write-Host

[$(Get-Date)] HDP Active

Use Ctrl-C in workflow to

terminate

Seconds 300

Start-Sleep
